#' Function creates a bar plot of temperature.
#' Instead of a normal bar plot, each bars is represented as line segments.
#' Each of these line segments are coloured differently to reflect the
#' reference climatology.
#'
#' @param plot_data data frame of station data; must have columns angle, tmin and tmax.
#' Angle corresponds to the day of the year, see \code{add_angle()}. If rainfall circles
#' are to be added
#' then plot_data must also have a column called rf_scale, for rescaled
#' rainfall, see \code{add_scaled_rainfall()}.
#' @param mid_quantiles This is a vector, that gives the y-coordindates for the
#' start and end of each line segemnt.
#' To use segments relative to reference climatology use \code{get_climatology_quantiles()}.
#' @param tmin_min Double giving the coldest temperature on record.
#' Needed for plotting line segments outside the range of the reference climatology.
#' @param tmax_min Double giving the hottest temperature on record.
#' Needed for plotting line segments outside the range of the reference climatology.
#' @param color_palette This will be used to plot the line segments of each quantile.
#' (Default is generated by create_color_palette()).
#' @param white_shift Optional double that shifts the bar plot by this amount
#' for aesthetic reasons (defult is 0.25).
#'
#' @return Returns a bar plot where each bar corresponds to a day of the
#' year. The start of the bar is the minimum temperature for that day and
#' end of the bar is the maximum temperature. The bar is created using line
#' segements which are coloured according the the reference climatology, given
#' by mid_quantiles.
#'
#' @examples
#' tmin = sin(seq(0, 2*pi, length.out = 360)) + rnorm(360, 20, 3)
#' plot_data = data.frame(angle = 1:360,
#'     tmin = tmin,
#'     tmax = tmin + 10)
#' mid_quantiles = seq(18, 28, length.out = 10)
#' tmin_min = min(plot_data$tmin) - 1
#' tmax_max = max(plot_data$tmax) + 1
#' create_temperature_bar_plot(plot_data, mid_quantiles,
#'    tmin_min, tmax_max)
#'
create_temperature_bar_plot <- function(plot_data, mid_quantiles,
                            tmin_min, tmax_max, color_palette,
                            white_shift = 0.25
                            ){

  if(nrow(plot_data) > 366){
    warning("There is more than one years worth of data")
  }

  if(missing(color_palette)){color_palette = create_colour_palette()}

  # plot set up
  temp_plot <- ggplot(data = plot_data)
  palette_len = length(color_palette)
  break_len = length(mid_quantiles)
  plot_quantiles = c(-10^6, mid_quantiles, 10^6) # extend quantile range for later climatology
  num_intervals = length(plot_quantiles) - 1

  # create a line segment between each quantile of a different colour
  # this allows the bar plot to have multiple colours|
  # this is in a loop because it is recursive and adds to the plot each time
  for(i in 1:num_intervals){

  # plots each line segment
  temp_plot <- add_temperature_bars(temp_plot, df = plot_data,
                                    y_min = plot_quantiles[i], y_max = plot_quantiles[i+1],
                                    col_val = color_palette[i/num_intervals * palette_len],
                                    tmin_min = tmin_min, tmax_max = tmax_max,
                                    white_shift = white_shift)

  }

  return(temp_plot)

}
